### Практическое задание к Уроку №1 “Вычисления с помощью Numpy”

In [4]:
import numpy as np

### Задание 1 


Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.


In [3]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [8]:
a.mean(axis = 0)

array([2. , 8.4])

In [11]:
mean_a = np.mean(a, axis = 0)
mean_a

array([2. , 8.4])

### Задание 2



Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

Способ 1

In [13]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Способ 2

In [14]:
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3


Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.


In [47]:
# Способ 1
v = a_centered[:, :1]
v = v.flatten()
c = a_centered[:, 1:]
c = c.flatten()
a_centered_sp = np.dot(v, c)
a_centered_sp

8.0

In [33]:
# Способ 2
x = a_centered[:,0]
y = a_centered[:,1]
a_centered_sp = np.dot(x, y)
a_centered_sp

8.0

In [36]:
# Число наблюдений равняется числу строк
N = a.shape[0]
N

5

In [40]:
a_centered_cov = a_centered_sp/(N-1)
a_centered_cov

2.0

### Задание 4

В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [49]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])

Элемент равен искомому значению ковариации

# Практическое задание к Уроку №1 “Работа с данными в Pandas”

### Задание 1



Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:  
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники']

In [51]:
import pandas as pd

In [55]:
authors = pd.DataFrame({'author_id':[1, 2, 3],
                  'author_name':['Тургенев', 'Чехов', 'Островский']}, columns=['author_id', 'author_name'])
authors


author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [56]:
books = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3], 
                     'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                   'price':[350, 400, 250, 600, 430, 550, 620]})
books

author_id            book_title  price
0          1           Отцы и дети    350
1          1                 Рудин    400
2          1     Дворянское гнездо    250
3          2      Толстый и тонкий    600
4          2       Дама с собачкой    430
5          3                 Гроза    550
6          3  Таланты и поклонники    620

### Задание 2



Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.

In [57]:
authors_price = pd.merge(authors, books, on = 'author_id', how = 'inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    350
1          1    Тургенев                 Рудин    400
2          1    Тургенев     Дворянское гнездо    250
3          2       Чехов      Толстый и тонкий    600
4          2       Чехов       Дама с собачкой    430
5          3  Островский                 Гроза    550
6          3  Островский  Таланты и поклонники    620

### Задание 3



Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

In [59]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name            book_title  price
6          3  Островский  Таланты и поклонники    620
3          2       Чехов      Толстый и тонкий    600
5          3  Островский                 Гроза    550
4          2       Чехов       Дама с собачкой    430
1          1    Тургенев                 Рудин    400

### Задание 4



Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.

In [67]:
df_1 = authors_price.groupby('author_name').agg({'price': 'max'}).rename(columns={'price':'max_price'})
df_2 = authors_price.groupby('author_name').agg({'price': 'min'}).rename(columns={'price':'min_price'})
df_3 = authors_price.groupby('author_name').agg({'price': 'mean'}).rename(columns={'price':'mean_price'})
df_3['mean_price'] = df_3['mean_price'].astype(int)
authors_stat = pd.concat([df_1, df_2, df_3], axis = 1)
authors_stat


max_price  min_price  mean_price
author_name                                  
Островский         620        550         585
Тургенев           400        250         333
Чехов              600        430         515

### Задание 5**



Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].
Просмотрите документацию по функции pd.pivot table с помощью вопросительного знака.
Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy.
Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.

In [68]:
cover = pd.DataFrame({'cover':['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']})
authors_price = pd.concat([authors_price, cover], axis = 1)
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    350  твердая
1          1    Тургенев                 Рудин    400   мягкая
2          1    Тургенев     Дворянское гнездо    250   мягкая
3          2       Чехов      Толстый и тонкий    600  твердая
4          2       Чехов       Дама с собачкой    430  твердая
5          3  Островский                 Гроза    550   мягкая
6          3  Островский  Таланты и поклонники    620   мягкая

In [75]:
book_info = pd.pivot_table(authors_price, values='price', index=['author_name'],
                    columns=['cover'], aggfunc=np.sum, fill_value=0)
book_info

cover        мягкая  твердая
author_name                 
Островский     1170        0
Тургенев        650      350
Чехов             0     1030

In [76]:
book_info.to_pickle('book_info.pkl')

In [77]:
book_info2 = pd.read_pickle('book_info.pkl')

In [78]:
book_info2

cover        мягкая  твердая
author_name                 
Островский     1170        0
Тургенев        650      350
Чехов             0     1030

In [79]:
book_info

cover        мягкая  твердая
author_name                 
Островский     1170        0
Тургенев        650      350
Чехов             0     1030

In [80]:
book_info == book_info2

cover        мягкая  твердая
author_name                 
Островский     True     True
Тургенев       True     True
Чехов          True     True